# Default values for csi-plugin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: shubham192001/csi-plugin
  tag: latest

name: my-controller-plugin
labels:
  app: my-controller-plugin

serviceAccount:
  name: csi-sa

storageClass:
  name: sample-storage-class
  provisioner: sample.csi.plugin
  volumeBindingMode: Immediate
  labels:
    app: sample-app
