apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-cr
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - get
  - delete
  - update
  - create
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  - volumeattachments/status
  - storageclasses
  - csinodes
  verbs:
  - patch
  - get
- nonResourceURLs:
  - "/api/v1/events"
  verbs:
  - create
  - list
  - watch
