apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: controller-plugin
  name: controller-plugin # The name of this deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller-plugin
  template:
    metadata:
      labels:
        app: controller-plugin
    spec:
      serviceAccountName: csi-sa #Name of the Service Account Present for deploying the controller
      containers:
      - image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0  # Use this image for the external-provisioner container
        name: external-provisioner
        args:
        - "--csi-address=$(CSI_ENDPOINT)"
        env:
        - name: CSI_ENDPOINT
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        volumeMounts:
        - mountPath: /var/lib/csi/sockets/pluginproxy
          name: domain-socket
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
      - image: k8s.gcr.io/sig-storage/csi-attacher:v3.5.0 # Use this image for the external-attacher container
        name: external-attacher
        args:
        - "--csi-address=$(CSI_ENDPOINT)"
        - "-v=5"
        env:
        - name: CSI_ENDPOINT
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        volumeMounts:
        - name: domain-socket
          mountPath: /var/lib/csi/sockets/pluginproxy
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
      - image: shubham192001/csi-plugin:latest #Main Container for the csi controller
        name: csi-controller-driver
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
        args:
        - "--endpoint=$(CSI_ENDPOINT)"
        - "--token=$(DO_TOKEN)"
        env:
          - name: CSI_ENDPOINT
            value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
          - name: DO_TOKEN  # Environment variable for the DigitalOcean access token
            valueFrom:
              secretKeyRef:
                name: do-token # The name of the secret
                key: access-token # The key within the secret
        volumeMounts:
        - mountPath: /var/lib/csi/sockets/pluginproxy
          name: domain-socket
      volumes:
      - name: domain-socket
        emptyDir: {}
